library(mnormt)     # must be installed
library(tlrmvnmvt)  # must be installed
library(mvtnorm)    # must be installed
library(patchwork)  # must be installed
library(ggplot2)    # must be installed
library(gridExtra)  # must be installed
library(mvCensored) # must be installed

ls("package:tlrmvnmvt")
ls("package:mvtnorm")

packageVersion("mnormt")    # must be 2.1.1
packageVersion("mvtnorm")   # must be 1.1.3
packageVersion("tlrmvnmvt") # must be 1.1.2

rm(list = ls())

# To begin with, we set up the values of the true parameters used to generate the data

ar1_cor <- function(n, rho){

  exponent <- abs(matrix(1:n - 1, nrow = n, ncol = n, byrow = TRUE) - (1:n - 1))

  return(rho^exponent)

}

p <- 3   # number of rows of the location, skewness and row covariance matrices

q <- 4   # number of columns of the location, skewness and column covariance matrices

# Definition the true location matrix

M <-  matrix(data = c(1, 2, 1, 2,
                      2, 2, 1, 1,
                      3, 3, 2, 3), p, q, byrow = TRUE)

# Definition of the true skewness matrix

A <-  matrix(data = c(-1,-2,-1,-2,
                      2,-2, 1,-1,
                      3,-3, 2,-3), p, q, byrow = TRUE)

# Definition of the true row covariance matrix

U  <- ar1_cor(p, rho = 0.4) * 1.5

# Definition of the true column covariance matrix (whose determinant equals one to avoid identifiability issues)

V <- ar1_cor (q, rho = 0.8)

V <- V / det(V)^(1 / q)

# We redefine the Frobenius norm here for completeness sake

Frobenius_Norm <- function(A) {

  sqrt(sum(A^2))

  return(sqrt(sum(A^2)))

}

# Set seed for reproducibility

set.seed(123)

counter <- 0

# Here, we generate the data used to construct the box plots

Box_Plot_MVSN_Censored_Data <- function(location_matrix,
                                        skewness_matrix,
                                        row_covariance_matrix,
                                        column_covariance_matrix,
                                        censoring,
                                        Ind,
                                        number_of_samples,
                                        number_of_simulations,
                                        max_attempts){

  # Pre-allocate storage

  p <- nrow(row_covariance_matrix)

  q <- ncol(column_covariance_matrix)

  MVSN_Censored_M                 <- array(0, dim = c(p, q, number_of_simulations)) # this variable is used to store the estimates of M under censoring

  MVSN_Censored_A                 <- array(0, dim = c(p, q, number_of_simulations)) # this variable is used to store the estimates of A under censoring

  MVSN_Censored_Sigma             <- array(0, dim = c(p, p, number_of_simulations)) # this variable is used to store the estimates of Sigma under censoring

  MVSN_Censored_Psi               <- array(0, dim = c(q, q, number_of_simulations)) # this variable is used to store the estimates of Psi under censoring

  Frobenius_MVSN_Censored_M       <- numeric(number_of_simulations)                 # this variable is used to store the distance between M and its estimates

  Frobenius_MVSN_Censored_A       <- numeric(number_of_simulations)                 # this variable is used to store the distance between A and its estimates

  Frobenius_MVSN_Censored_Sigma   <- numeric(number_of_simulations)                 # this variable is used to store the distance between Sigma and its estimates

  Frobenius_MVSN_Censored_Psi     <- numeric(number_of_simulations)                 # this variable is used to store the distance between Psi and its estimates

  MVSN_Censored_BIC               <- numeric(number_of_simulations)                 # this variable is used to store the BIC value related to each simulation

  MVSN_Censored_Log_Likelihood    <- numeric(number_of_simulations)                 # this variable is used to store the Log-Likelihood related to each simulation

  # Loop number_of_simulations times

  for (i in 1:number_of_simulations) {

    # The auxiliary_variable1 shall be used to store the outputs of the "mv_ecm" function

    auxiliary_variable1 <- NULL

    # Set up the number of attempts variable to equal one

    attempt <- 1

    # Start the "success" variable as false so we can apply the "try" function

    success <- FALSE

    while (attempt <= max_attempts && !success) {

      # This variable stores the samples generated by the MVSN distribution in the presence of censoring

      samples <- rmatrix_censored(n = number_of_samples,
                                  cens = censoring,
                                  Ind = Ind,
                                  M = location_matrix,
                                  U = row_covariance_matrix,
                                  V = column_covariance_matrix,
                                  A = skewness_matrix,
                                  dist = "SN")

      # These lines stores the parameters that shall be useful from now on

      X.cens <- samples$X.cens

      cc <- samples$cc

      LS <- samples$LS

      # Try to run your function

      auxiliary_variable1 <- try(mv_ecm("MVSNC", X.cens, cc = cc, LS = LS, precision = 1e-07, MaxIter = 20), silent = TRUE)

      # Check if it worked

      if (!inherits(auxiliary_variable1, "try-error")) {

        success <- TRUE

      } else {

        attempt <- attempt + 1

        counter <- attempt

        # Optional: you can print a silent message for debugging
        # message(paste("Attempt", attempt - 1, "failed — retrying..."))

      }
    }

    # Handle case where all attempts failed

    if (!success) {

      message("EM.MatrixSN.cens failed after all attempts.")

      auxiliary_variable1 <- NULL

    }

    MVSN_Censored_M[ , , i]            <- auxiliary_variable1$mu

    MVSN_Censored_A[ , , i]            <- auxiliary_variable1$A

    MVSN_Censored_Sigma[ , , i]        <- auxiliary_variable1$Sigma

    MVSN_Censored_Psi[ , , i]          <- auxiliary_variable1$Psi

    Frobenius_MVSN_Censored_M[i]       <- Frobenius_Norm(auxiliary_variable1$mu - location_matrix)

    Frobenius_MVSN_Censored_A[i]       <- Frobenius_Norm(auxiliary_variable1$A - skewness_matrix)

    Frobenius_MVSN_Censored_Sigma[i]   <- Frobenius_Norm(auxiliary_variable1$Sigma - row_covariance_matrix)

    Frobenius_MVSN_Censored_Psi[i]     <- Frobenius_Norm(auxiliary_variable1$Psi - column_covariance_matrix)

    MVSN_Censored_BIC[i]               <- auxiliary_variable1$BIC

    MVSN_Censored_Log_Likelihood[i]    <- auxiliary_variable1$loglik

  }

  norms_list <- list(MVSN_Censored_M = MVSN_Censored_M,
                     MVSN_Censored_A = MVSN_Censored_A,
                     MVSN_Censored_Sigma = MVSN_Censored_Sigma,
                     MVSN_Censored_Psi = MVSN_Censored_Psi,
                     Frobenius_MVSN_Censored_M = Frobenius_MVSN_Censored_M,
                     Frobenius_MVSN_Censored_A = Frobenius_MVSN_Censored_A,
                     Frobenius_MVSN_Censored_Sigma = Frobenius_MVSN_Censored_Sigma,
                     Frobenius_MVSN_Censored_Psi = Frobenius_MVSN_Censored_Psi,
                     MVSN_Censored_BIC = MVSN_Censored_BIC,
                     MVSN_Censored_Log_Likelihood = MVSN_Censored_Log_Likelihood
  )

  return(norms_list)

}

# This part of the code is used to test the validity of the Box_Plot_Data function

test1 <- Box_Plot_MVSN_Censored_Data(location_matrix = M,
                                     skewness_matrix = A,
                                     row_covariance_matrix = U,
                                     column_covariance_matrix = V,
                                     censoring = 0.15,
                                     Ind = 1,
                                     number_of_samples = 50,
                                     number_of_simulations = 5,
                                     max_attempts = 100)
print(test1)

